language: python
python:
    - "2.7"
    
install:
    - pip install tox-travis
    
script:
    - tox
    
env:
    - NUMPY="1.9"
    - NUMPY="1.10"
    - NUMPY="1.11"
    - NUMPY="1.12"
    - NUMPY="1.13"